# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-13 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhsauth', '0003_user_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gocardless_user',
            field=models.BooleanField(default=False),
        ),
    ]
