# Generated by Django 2.2.16 on 2020-09-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lhsauth', '0004_user_gocardless_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gocardless_user',
        ),
    ]
