FROM debian:10.8

RUN apt-get update && \
    apt-get -y install postfix postfix-pcre mutt mailutils

# RUN cp /etc/services /var/spool/postfix/etc/services
# RUN cp /etc/resolv.conf /var/spool/postfix/etc/resolv.conf

# RUN mkdir /config && \
#     mv /etc/postfix/main.cf /config/main.cf && \
#     mv /etc/postfix/master.cf /config/master.cf && \
#     ln -s /config/main.cf /etc/postfix/main.cf && \
#     ln -s /config/master.cf /etc/postfix/master.cf

CMD ["postfix", "start-fg"]
