# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 19:40
from __future__ import unicode_literals

from django.db import migrations
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='from_date',
            field=main.models.DateTimeDateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='to_date',
            field=main.models.DateTimeDateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_date',
            field=main.models.DateTimeDateField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=main.models.DateTimeDateField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=main.models.DateTimeDateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=main.models.DateTimeDateField(),
        ),
    ]
