# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 19:43
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


def set_site_name(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    try:
        site = Site.objects.get(id=settings.SITE_ID)
    except Exception as e:
        print(e)
        site = Site(id=settings.SITE_ID)
    site.domain = site.name = settings.DOMAIN_NAME
    site.save()

def undo_site_name(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    try:
        site = Site.objects.get(id=settings.SITE_ID)
    except Exception as e:
        print(e)
        site = Site(id=settings.SITE_ID)
    site.domain = site.name = 'example.com'
    site.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fix_dates'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(set_site_name, undo_site_name),
    ]
