# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='disabled_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='hackney',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=main.models.FlourishPasswordField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_period',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='terminated',
            field=models.BooleanField(default=False),
        ),
    ]
