# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-13 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('resource_type', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('links', models.TextField()),
                ('details', models.TextField()),
            ],
        ),
    ]
