# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-09 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_type', models.IntegerField(choices=[(1, 'Bank Payment'), (2, 'GoCardless')])),
                ('payment_state', models.IntegerField(choices=[(1, 'Pending'), (2, 'Succeeded'), (3, 'Failed')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
