# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-09 12:11
from __future__ import unicode_literals

from django.db import migrations

def migrate_transactions(apps, schema_editor):
    Transaction = apps.get_model('main', 'Transaction')
    Payment = apps.get_model('lhspayments', 'Payment')

    for t in Transaction.objects.all():
        p = Payment()
        p.id = t.fit_id
        p.timestamp = t.timestamp
        p.user = t.user
        p.amount = t.amount
        p.payment_type = 1
        p.payment_state = 2
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lhspayments', '0001_initial'),
        ('main', '0003_set_site_name'),
    ]

    operations = [
        migrations.RunPython(migrate_transactions)
    ]
