# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-09 12:11
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('lhspayments', '0001_initial'),
        ('main', '0003_set_site_name'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO lhspayments_payment(id,timestamp,amount,payment_type,payment_state,user_id)
            SELECT fit_id,timestamp,amount,1,2,user_id FROM transactions
        """)
    ]
