# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-07 14:49
from __future__ import unicode_literals

from django.db import migrations
from django.db import connection


def insert_flourish_table(apps, schema_editor):
	# this is written so that if the item already exists,
	# it will not be added again, therefore it is safe on both
	# new installs and as an update to existing ones
	query = """
		INSERT INTO flourish_tables (tablename) 
			SELECT 'lhspayments_payment' WHERE NOT EXISTS (
				SELECT * FROM flourish_tables WHERE tablename = 'lhspayments_payment'
			);
		"""
	with connection.cursor() as cursor:
		cursor.execute(query)


class Migration(migrations.Migration):

    dependencies = [
        ('lhspayments', '0002_importoldtransactions'),
    ]

    operations = [
    	migrations.RunPython(insert_flourish_table)
    ]
